### ISSUE TITLE
Continue not working in Android and MacOS

### ISSUE THREAD

**Issue by Tmax469** [GlowPuff/ImperialCommander2#1]
I have tried multiple times within different missions to select CONTINUE from the main menu and it is not working in Imperial Commander 2 for Android or Mac. Works fine using Imperial Commander (original), so I don't think it is a permissions issue.

**Comment by Noldorion** [comment]
The Save currently only works in Classic mode. Saving for Saga mode is planned for the next update. See also here:

https://boardgamegeek.com/thread/2881226/imperial-commander-2-known-bugs-glitches

**Comment by Tmax469** [comment]
Thanks for the info and the super-fast response. Love the app!!
