### ISSUE TITLE
Cannot add Ally to scenario.

### ISSUE THREAD

**Issue by stooge4444** [GlowPuff/ImperialCommander2#100]
Continue to receive a stack-trace when trying to add an Ally upon starting a new scenario; the error happens immediately when clickign "Add Ally". Full error is "InvalidOperationException:Sequence contains no matching element."  I tried an existing campaign as well as a brand new campaign; I attempted to continue  a campaign of the Core Game (in v2.2.3) and never had issues with this in the previous version I was using (v2.1.5).

When I revert back to 2.1.5, I had no issues thus it's somewhere between then and now.

**Comment by Noldorion** [comment]
Hello!

Thanks for letting us know! The issue has been reported and will be fixed in the next version. For details (and a workaround), see here:

https://github.com/GlowPuff/ImperialCommander2/issues/84

**Comment by stooge4444** [comment]
OK great.  When I searched known issues, I couldn't find this issue.  I know see that the other one only had the error listed in the screenshot and not text lol.

**Comment by stooge4444** [comment]
#duplicate

**Comment by stooge4444** [comment]
I just looked at the sequence again and my flow is a little different.  Since it's launching a mission from a campaign, I actually can't reproduce the workaround.  Just wanted to make sure the test path works from within a campaign.

**Comment by GlowPuff** [comment]
No worries, it's fixed for Missions launched from a Campaign, also.
