### ISSUE TITLE
Custom Campaigns on Amazon Fire Tablet

### ISSUE THREAD

**Issue by AdrianTP** [GlowPuff/ImperialCommander2#105]
My only Android tablet is a cheapo Amazon Fire Tablet, which I would like to get some use out of by running Imperial Commander 2.

I am unable to move files into the `Android/data/com.GlowPuff.ImperialCommander2/files/CustomCampaigns` folder. When moving files I am only offered the `media` folder as a destination within the `Android` folder. Is it possible to add the ability to point to a custom file location for custom campaigns within the app? Either that, or enable pointing to the `Downloads` directory, or the `Documents` directory? (assuming those aren't stored at different filepaths for each Android device manufacturer).

EX File Manager lets me at least see the `data` directory, but shows no contents. I would prefer not to have to root this device.

**Comment by AdrianTP** [comment]
I found a workaround: X-Plore file explorer fromthe Amazon App Store has an incredibly unintuitive interface, but after 5 minutes of fiddling and granting of various permissions along the way, I was able to successfully copy the custom campaigns into the correct folder.

**Comment by GlowPuff** [comment]
Awesome, glad you got it working. ⭐

**Comment by AdrianTP** [comment]
Worth noting: it consistently crashed after a few minutes running on the Amazon Fire Tablet, so I ended up just running it on a laptop.
