### ISSUE TITLE
Wrong symbol for General Weiss instruction 4 ?

### ISSUE THREAD

**Issue by ilujito2** [GlowPuff/ImperialCommander2#109]
Instruction.json -> General Weiss -> Instruction group 4

Current 2nd instruction:

_{A} Roll 1 yellow die. A Rebel within 3 spaces suffers {H} equal to the {H} results and {C} equal to the {C} results. Target the hero who has suffered the least {C}._

I think it's rather:

_{A} Roll 1 yellow die. A Rebel within 3 spaces suffers {H} equal to the {H} results and {C} equal to the **{B}** results. Target the hero who has suffered the least {C}._

Because there is no {C} symbol on SWIA dice.

This would require a change in IC2 and TranslatorModernApp.

**Comment by Noldorion** [comment]
Yes, correct. Fixed it and created a pull request.
