### ISSUE TITLE
'nul' text for Core > Chain of Command

### ISSUE THREAD

**Issue by zuckel** [GlowPuff/ImperialCommander2#11]
On a fresh install of 2.0.23 when starting a new Saga game and selecting the Core > Chain of Command mission, there is a short text saying 'nul' above the Difficulty chooser. I haven't seen a text in this place for any of the other missions.

**Comment by GlowPuff** [comment]
Good find, thank you.  I had fixed this elsewhere, but I missed the one other spot where the app parses "additional info".  Bonus - this helped me find and fix another very minor bug, also.
