### ISSUE TITLE
Corrections Spanish translation

### ISSUE THREAD

**Issue by AzzameenF18** [GlowPuff/ImperialCommander2#15]
Hi, I have corrected (minor errors) the Spanish translation (I don't know who the original author is, but congratulations, great job).
[Resources.zip](https://github.com/GlowPuff/ImperialCommander2/files/10173981/Resources.zip)

I also add the images of the enemies (like the ones in the official app). Besides, they take up a little less space
[All icons.zip](https://github.com/GlowPuff/ImperialCommander2/files/10173997/All.icons.zip)

I am reworking the tiles, to remove the laces, in case you are interested (when I finish them, I will send them).
Original:
![Core_17A original](https://user-images.githubusercontent.com/92848798/206125382-0d38672c-cb0f-4fb1-abfd-c46f29279cda.png)

Edited:
![Core_17A mod](https://user-images.githubusercontent.com/92848798/206125393-386749c0-f9bf-4ef6-b281-4374dc7dd7c4.png)

**Comment by GlowPuff** [comment]
Wow, very nice!! Thank you for the updated translations and the icons.

As for the tiles, that's a lot of work, but if you want to do it, that's great!  I just ask they be kept uncompressed throughout the process (no JPG format) and finally saved in PNG format so there are no visible compression artifacts.
