### ISSUE TITLE
New font types

### ISSUE THREAD

**Issue by AzzameenF18** [GlowPuff/ImperialCommander2#16]
Hello, looking at the Imperial Assault manuals, I have found the fonts used. You can download them in a zip file, along with an image of each font. I hope you find it useful. Best regards
[Font types.zip](https://github.com/GlowPuff/ImperialCommander2/files/10252865/Font.types.zip)

**Comment by GlowPuff** [comment]
AWESOME thank you!  I will see what I can do with these!
