### ISSUE TITLE
Tag showing in German Tutorial 2

### ISSUE THREAD

**Issue by philsuess** [GlowPuff/ImperialCommander2#17]
Hi there, loving the app.

Here is a tag visible in the German version of Tutorial 2:

![20221221_075734](https://user-images.githubusercontent.com/17199306/208841758-5421fd21-82b5-4942-a262-f72da3a142cd.jpg)

Happy holidays!

Phil

**Comment by philsuess** [comment]
Further into the tutorial there is another tag showing:

![16716077530338688042235702664704](https://user-images.githubusercontent.com/17199306/208846023-94e319c0-199f-49c8-9197-f006c27edc9b.jpg)

**Comment by philsuess** [comment]
Further down there is an English text

![16716094754492402676178071328614](https://user-images.githubusercontent.com/17199306/208851259-2dc83417-c70f-4f42-90cf-7a99483908e3.jpg)

**Comment by philsuess** [comment]
![Uploading 16716097720792103908105435357046.jpg…]()

**Comment by philsuess** [comment]
![16716098288364101588923059617365](https://user-images.githubusercontent.com/17199306/208852233-4dea460e-3060-447d-b4bb-2c0c317f003e.jpg)

More tags.

**Comment by philsuess** [comment]
There are some more visible tags and some of the boxes are in English.

I hope these help.

**Comment by GlowPuff** [comment]
Fixed - thank you for the edits!
