### ISSUE TITLE
Right-clicking the imperial unit does not show the activation screen again, instead shows the unit card

### ISSUE THREAD

**Issue by klauskopec** [GlowPuff/ImperialCommander2#19]
Not 100% sure whether this is a misunderstanding on my side about what right-click on the unit icon is supposed to do in this situation or an actual bug, but it seems like a bug to me.

In tutorial 2 (but also once before in tutorial 1 or 2) at least the German text mentions that one can click the eye to hide the tutorial and then right-click the enemy icon to show the activation screen again. In the current version of IC2, it's not the activation screen that's shown, but the unit card. This makes it impossible to see the actions again after closing the original activation dialog.

This is the text referring to re-opening the activation sceen:
![IC2 bug (german texts)](https://user-images.githubusercontent.com/7880831/210353062-da4c9f9c-db37-4a09-9e09-c2c99e739041.png)

Instead of the activation dialog, right-clicking on Vader shows the unit card:
![IC2 bug (german texts) 2](https://user-images.githubusercontent.com/7880831/210353160-e443f46e-6755-427d-9315-48360ba2f589.png)

**Comment by Noldorion** [comment]
I can confirm this is happening, but ONLY when right-clicking the thumbnail after clicking the eye icon. If you close all text windows and THEN right-click the thumbnail, it shows the activation window as intended.

**Comment by GlowPuff** [comment]
Thank you - fixed.
