### ISSUE TITLE
Custom missions on Android version

### ISSUE THREAD

**Issue by jph33** [GlowPuff/ImperialCommander2#28]
I noticed that the custom folder is located in Android\data\com.GlowPuff.ImperialCommander2\files\CustomMissions but starting with Android 11 we are not allowed to copy the custom missions into this folder. Can the folder be stored somewhere else for android version? Thanks for the feeadbacks

**Comment by vida2001** [comment]
is this on the roadmap to be fixed? I am considering buying an android tablet just for this app, we like it that much, and I am worried to run into the next issue rofl

**Comment by GlowPuff** [comment]
It is... it looks like Google has a flag I can set in the app's manifest to instruct Android to continue to allow the old folder permissions and locations.

**Comment by GlowPuff** [comment]
I'm setting the app to target Android 9 (API 28) and setting the "requestLegacyExternalStorage" flag in the manifest.  This should sidestep the Android 11 scoped storage situation.
