### ISSUE TITLE
Font issues (capitalization, line spacing)

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ImperialCommander2#30]
This was predicted, but since the font change, some capitalizations are inconsistent, and there are various line spacing issues, see screenshots. Should I go through the app and list everything I can find?

![grafik](https://user-images.githubusercontent.com/67169098/223856518-bc7926c3-3551-40cb-95ed-1085b96d7a52.png)
![grafik](https://user-images.githubusercontent.com/67169098/223856572-9f7b0644-b769-452f-a4cf-33376f760eb5.png)

**Comment by GlowPuff** [comment]
Ah yes, this was very much expected.  I fixed the line spacing and capitalization issues for the new font on as many items as I could come across, but it was in no way an exhaustive search.  I don't think I even looked at Classic mode for anything wrong!  I've been fixing them as I come across them working on the next update, but yes, it would help a lot to have a list of everything you can find.

**Comment by Noldorion** [comment]
Alright! I'll systematically go through the app on the weekend and collect everything I find.

**Comment by Noldorion** [comment]
Found the following:
![grafik](https://user-images.githubusercontent.com/67169098/224016935-72ad197c-7cd4-4e93-ac81-de31c75fd3e7.png)
![grafik](https://user-images.githubusercontent.com/67169098/224016972-753c6b29-cd84-4a73-aaf1-58994a577967.png)
![grafik](https://user-images.githubusercontent.com/67169098/224016993-8d86e5e7-bb22-41b5-8950-925f22e8d922.png)
![grafik](https://user-images.githubusercontent.com/67169098/224017044-45a6c299-2ceb-4219-9ab2-78e425045e21.png)
![grafik](https://user-images.githubusercontent.com/67169098/224017095-7de515f0-244d-4a23-ae44-1af5efaa4c39.png)
![grafik](https://user-images.githubusercontent.com/67169098/224017113-cacd8234-437e-4ba5-b2ae-1e8f42da1a12.png)
![grafik](https://user-images.githubusercontent.com/67169098/224017127-d594598e-6706-4707-a46f-28f47af64d04.png)
![grafik](https://user-images.githubusercontent.com/67169098/224017135-23ead46a-ee98-4f79-bf8d-0c8fee49ddb4.png)
![grafik](https://user-images.githubusercontent.com/67169098/224017178-c1173cf6-a315-4d25-8a9b-198ef96febb4.png)
