### ISSUE TITLE
Modifications showing up for the wrong groups

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ImperialCommander2#31]
Occasionally, some modifications for thumbnails (for example: +13 Health) show up not only in the designated thumbnail, but also in other thumbnails. (Example: Mission “The Anchorhead Affair”). I think you might have solved that already? Unfortunately, while I encounter it occasionally, I can’t reliably reproduce it.

**Comment by GlowPuff** [comment]
This was supposed to have been fixed in the last update:
- The modification box for a particular enemy no longer displays on every other group in the mission

Is it still bugged?

**Comment by Noldorion** [comment]
Whoops, didn't notice that, I was just going through the old bug list. I'll close it!
