### ISSUE TITLE
Add Medpac Management to gameplay screen

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ImperialCommander2#33]
Someone suggested adding medpac management to the gameplay screen, and even provided some [artwork](https://boardgamegeek.com/thread/2611941/article/41409691#41409691):

![grafik](https://user-images.githubusercontent.com/67169098/224148003-d89da1b8-31bb-4a39-9e56-23a548de4162.png)

Medpacs could be shown in the gameplay screen, with a manual counter. The counter starts with 1 at each mission and can be freely increased / decreased by the players. You can also click on it to open a window with the following text:

“A hero can use a medpac when they perform a rest action, and an ally figure can use a medpac as an action. When a figure uses a medpac, it recovers 5 {H}. Medpacs can be found in crates.

[Use] [Cancel]”

Clicking “Use” decreases the counter by 1 and displays the message: “Recover 5 {H}.”

![grafik](https://user-images.githubusercontent.com/67169098/224148051-3af071ff-dc7e-45a5-a10d-e7c9b10823af.png)

**Comment by GlowPuff** [comment]
Done. 🏆
