### ISSUE TITLE
Figure pack management / reworked banned groups

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ImperialCommander2#34]
There are currently three to four conflicting sources for banned groups:

- Figure Packs (those should be banned automatically unless the player deselects them, which - I think - doesn't work in Saga at the moment?)
- Banned Groups as dictated by the basic mission presets we implemented a while ago.
- Banned Groups as dictated by the Saga mission editor.
- Banned Groups set by the player.

Right now, I'm not quite sure what takes preference here anymore. I assume they are additive - so when basic mission settings ban a few groups, and the Saga mission bans a few more, they are added together? If yes, I think this is how it should be.

But figure pack ownership remains an issue. At the moment, players have to check the banned groups for each mission they play. I don't think this is a problem for experienced players, but since we're lowering the bar of entry at the moment, maybe we should take a look at it.

So I think it would be better if we added an option to select / deselect figure packs just like expansions. The good news: We don't need to implement all 40 figure packs. I checked, and 5 figure packs are enough, containing 8 deployment groups altogether.

The idea is:

- Just like a big expansion, those groups are unavailable for open groups unless they are activated in the menu. 
- Rename "Campaigns" to "Expansions" (something we were planning to do for the campaign manager anyway). 
- Add a sub-menu called "figure packs" were you can activate/deactivate figure packs. The good news are that we should even have all the translations.

![grafik](https://user-images.githubusercontent.com/67169098/224152347-308df46c-1b25-4978-8a5b-b0d646396a0e.png)

**Comment by GlowPuff** [comment]
Done.
