### ISSUE TITLE
Capitalization issues

### ISSUE THREAD

**Issue by jph33** [GlowPuff/ImperialCommander2#39]
Hi,
I found new non-capitalized strings:
- In the screen after lauching a new campaign mission but before starting it really:
![image](https://user-images.githubusercontent.com/71392645/227543373-37396be3-2b0c-4a1d-b392-6ff6dd977c54.png)
- In the main mission screen in the bottom right:
![image](https://user-images.githubusercontent.com/71392645/227543639-b81829e1-2ace-4946-a8b5-e9de91f2898f.png)
- In the activation page, perhaps the name of the group should be capitalized?
![image](https://user-images.githubusercontent.com/71392645/227595238-b317ca24-da32-456c-a5da-a833b890e669.png)

**Comment by GlowPuff** [comment]
Thanks!  Fixed for the next update.

**Comment by jph33** [comment]
Hi @GlowPuff I just tested your last code push and the last capitalization point is not solved. Is it expected or just missed?
Thanks for all your work!
jph33 / EloFip

**Comment by GlowPuff** [comment]
Hi, thanks!  Yes, looks like I accidentally left a line of code forcing the name to lower case.  Thank you, fixed now.
