### ISSUE TITLE
Wrong position of an image

### ISSUE THREAD

**Issue by jph33** [GlowPuff/ImperialCommander2#43]
Hi. Sorry if you already are aware of the existence of this pb.
With the very last deliveries i noticed in an Android Build a pb with the position of the image of a unit in the activation window. There was no pb with a windows Build.
![Screenshot_2023-05-08-09-23-49-875_com.GlowPuff.ImperialCommander2.jpg](https://user-images.githubusercontent.com/71392645/236883139-adc562c6-7aeb-4ddd-b152-597628a11060.jpg)

**Comment by GlowPuff** [comment]
Nice find, thank you!  The anchor point was fixed instead of using the top left of the container.  Any aspect ratio wider than 16:9 would cause the misplaced icon image that you're seeing.
