### ISSUE TITLE
New untranslated strings

### ISSUE THREAD

**Issue by jph33** [GlowPuff/ImperialCommander2#44]
Hi,
Wow the mission log is awesome!!!! Thanks for this evolution.
I found some untranslated fields in the mission log:
![PrtScr capture_77](https://github.com/GlowPuff/ImperialCommander2/assets/71392645/b6a7db9a-94f5-44f2-bdf5-4778aa68c337)

And here is the ui.json file for French:
[ui.json.txt](https://github.com/GlowPuff/ImperialCommander2/files/11461242/ui.json.txt)

**Comment by GlowPuff** [comment]
Awesome!  I'm so glad you like the log.  Nothing in the log panel is translated right now, so it's all English.  I'll be adding the new translation strings to the ui.json soon. 👍🏻

Thanks for the updated French ui.json! 🙏🏻
