### ISSUE TITLE
Mission Log untranslated strings

### ISSUE THREAD

**Issue by jph33** [GlowPuff/ImperialCommander2#45]
Hi,
I found some untranslated fields in the mission log:
![PrtScr capture_90](https://github.com/GlowPuff/ImperialCommander2/assets/71392645/36e48c48-941f-47d2-943c-47afc305d80c)
The deployment Event name and the Continue button are not translated.

**Comment by GlowPuff** [comment]
Thank you!  I also noticed ROUND wasn't using the translations.  All fixed now.

**Comment by jph33** [comment]
@GlowPuff btw i tried to Build an Android apk with your last deliveries but i am facing an error when trying to launch a mission or seeing the tiles.
Here is a screenshot. Any advice or perhaps it is normal ? For windows Build it works.
![Screenshot_2023-05-25-19-45-24-361_com.GlowPuff.ImperialCommander2.jpg](https://github.com/GlowPuff/ImperialCommander2/assets/71392645/96542225-3480-4daf-a3de-f5d0db851a80)

**Comment by GlowPuff** [comment]
Did you rebuild the Addressable Assets first?  After you change the build target, the Assets need to be rebuilt for that platform before building the actual app.  I haven't tested on Android yet, so this could be another issue entirely, but start with rebuilding the Assets.

In the Addressable Asset window (Window->Asset Management->Addressables->Groups), select Build->Update a Previous Build
![asset](https://github.com/GlowPuff/ImperialCommander2/assets/22311140/90afd868-936d-4218-9eef-47ae1f17f832)

**Comment by jph33** [comment]
Thanks @GlowPuff this was the pb. Thank you. A last question do add some parameters to make all apks compatible each others (recogniztion of the param save files, save games...)? For me each time a build an apk i have to redefine all my options and save files.

**Comment by GlowPuff** [comment]
That's interesting... When I install a new version of the app for testing, Android always asks me to "upgrade" the existing app.  And it keeps all the settings and saved files intact.  The app uses the same identifier (com.glowpuff.ImperialCommander2).  That alone, I believe, should make it "upgrade" existing installations without losing data.  I'm not sure what else to do about this.

**Comment by jph33** [comment]
Thanks For the answer. In fact i understood. I used to uninstall first then install the New version. On my tablet it keeps my settings and saves whereas on my cell phone everything is erased. So by now i will just install the New version without uninstalling the previous.
Thanks again
