### ISSUE TITLE
Expansion characters deplyed during tutorial with no expansions selected

### ISSUE THREAD

**Issue by jorgeluispena** [GlowPuff/ImperialCommander2#47]
Hi! Sorry for my English. It's not my mother tongue.

During Tutorial 3 in Spanish, in turn four or five if I remember well (while we were escaping to the shuttle), two extra groups were deployed: Jawas and  Hired Guns. I had no expansions whatsoever selected, just the Core Set. It was a fresh install of the Windows application and I did not mess with any Setting or extra configuration. I just changed the language to Spanish and tried the Tutorials in order.

**Comment by Noldorion** [comment]
Hello!

Can you please take a look in the expansions menu and check under "Figure Packs" if any figure packs are selected? Just to make sure 🙂

**Comment by jorgeluispena** [comment]
Hi Noldorion! I checked that no expansions and no figure packs were added by mistake prior to posting the Issue. I'm sorry if I was not clear about that point.

As I said, this was coming form a "clean" unzip of the Windows files, with no messing with any settings or configurations (sounds, volume, expansions, etc.). The only thing I did was playing the three tutorials by myself (in English), changed the language to Spanish, and played again the three tutorials with my kids (who do not speak or read English very well yet).

I'm now remembering an extra issue. In Tutorial 3, while playing in Spanish (I do not remember seeing this issue while playing in English), when I was asked to set tile Core 01A an extra tile Core 18A showed in the 3D map right next to the ship wreckage where there is no place to put 18A.

I'm sorry but I'm a noob using the app. I assume there is a way to check the map. Is there any difference in a map using one language or another? I would guess that languages are independent of that.

**Comment by jorgeluispena** [comment]
![image](https://github.com/GlowPuff/ImperialCommander2/assets/138615173/9e485ed2-bd72-49fd-a4fe-6bb21a780622)
I just took that screenshot. I opened Tutorial 3, went through the initial messages. When the app allowed it, I manually added Threat and showed the available units for deployment. And there you have it, Bantha and Dewback Ridres were available!

I hope this somehow helps and that you can see the screenshot.

**Comment by jorgeluispena** [comment]
BTW the same thing happens in the English Tutorial 3. It was kind of obvious that the language was not the issue, but here is the proof:
![image](https://github.com/GlowPuff/ImperialCommander2/assets/138615173/32320d62-1607-42b8-8b5c-cd97b47a6385)
The only difference is that this time I did not change the Threat level. I just only showed the Reserved Units (sorry if that is not the correct term).

**Comment by Noldorion** [comment]
Thanks! The language versions of the tutorials are all their own files, but they should be virtually the same. I checked them, and I can confirm the extra map piece - thanks for the find. I've updated it, the corrected version will be in the next update.

As for the expansion figures: We recently changed the way figure packs work, and this seems to only affect figure packs, so the problem probably comes from that. We'll take a look. Until then, you could just proxy the figures you don't have with other figures - all the stats should be in the app's deployment cards.

**Comment by GlowPuff** [comment]
I'm working on fixing this. 👍🏻

**Comment by GlowPuff** [comment]
aaaaaaand fixed.

**Comment by jorgeluispena** [comment]
Thanks for the fix!
