### ISSUE TITLE
64-bit ARM support for Android 13+

### ISSUE THREAD

**Issue by dhollinger** [GlowPuff/ImperialCommander2#50]
With the upcoming release of Android 14, none of the Google Pixel Products will be able to run 32-bit applications anymore and (rumors) are the Google will require 3rd party forks to stop supporting 32-bit applications to continue using Google Mobile Services on Android.

Probably best to look into supporting 64-bit Android or dropping support altogether.

**Comment by GlowPuff** [comment]
Thanks for the heads up!  I've changed the project build settings to IL2CPP and enabled ARM64 target support.  I've also enabled split target output, so the next release of IC2 will have both 32bit and 64bit APKs available for download.  I just did a test build and it worked, both APKs were created.  Looks like we're in good shape, thanks again. 👍🏻
