### ISSUE TITLE
Translation to Czech

### ISSUE THREAD

**Issue by Mikymart** [GlowPuff/ImperialCommander2#52]
Hello, is it possible to translate APP and missions to Czech language? I have tried to do it on Windows using the app, but my main OS is MacOS and I cannot find a way how to import translated files.

**Comment by GlowPuff** [comment]
Hello! Translations are handled by the community, so if someone is able and willing to do it, we can absolutely integrate it into the app. Most of the time, people do a few translations at a time.  Just doing the UI is a good starting point, then maybe the tutorials.  This is a nice way of getting to know how to do it. When you're done with the files, just send them to me, and I will build them into the app.
