### ISSUE TITLE
Feture request: automatic increase/decrease credits when buying/selling items

### ISSUE THREAD

**Issue by MrRosendahl** [GlowPuff/ImperialCommander2#53]
Well, the title says pretty much the whole story.
It would be a nice to have feature, and also perhaps that items that are too expensice are not purchaseable, perhaps faded out and button is inactivated.

Oh, and by the way, thank you for creating a great application!!

**Comment by GlowPuff** [comment]
I really like this idea, I'll put it on the list! 🤩

**Comment by GlowPuff** [comment]
Done!
