### ISSUE TITLE
Feature request: Sort tile count within missions

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ImperialCommander2#57]
A request from the forums: When tiles are placed during a mission, they are out of order. They could be ordered according to their tile number, and multiple tiles maybe even summarized like you did with the tile info popup before a mission (with a "x 2" for two tiles, for example).

![grafik](https://github.com/GlowPuff/ImperialCommander2/assets/67169098/ff1ea0fd-8f0c-43de-80fa-4a753330aa38)

**Comment by MrRosendahl** [comment]
Ah, yes that should be doable with a split and order!
