### ISSUE TITLE
"New" core tiles

### ISSUE THREAD

**Issue by AzzameenF18** [GlowPuff/ImperialCommander2#59]
Hi, I'm Pedro Millán, a long time ago, I offered to edit the tiles. Well, with a lot of delay (sorry) I'm sending you the ones from the core box. They are in the same format and size used by the app. I hope you like them and they can be integrated (I have removed the puzzle "holes"). 
[Core1.zip](https://github.com/GlowPuff/ImperialCommander2/files/13552143/Core1.zip)
[Core2.zip](https://github.com/GlowPuff/ImperialCommander2/files/13552148/Core2.zip)

On the other hand, I would like to "offer" to use the font Agency FB (https://www.dafontfree.net/agency-fb-regular/f64369.htm) For numerical values. Other font interesting (I think you already use it) is Teuton Fett (https://www.dafontfree.net/teuton-fett-regular/f24426.htm)

Thanks you!!! And i'm trying to make sure that the next package won't cost me so much.

**Comment by GlowPuff** [comment]
Hi Pedro, of course I remember you.  Wow - these look amazing!  GREAT work, thank you!  I'm sure everyone will appreciate this, as well.
