### ISSUE TITLE
Translation to Italian

### ISSUE THREAD

**Issue by Yexalel** [GlowPuff/ImperialCommander2#61]
Hi. I noticed app is not fully translated in italian. Can you fix it? I can help, if someone tell me what to do. 
Thank you very much

**Comment by GlowPuff** [comment]
Hello, our translations are supplied by community volunteers.  Only German and Spanish are currently *completely* translated.  All the other translations are incomplete.  

If you'd like to contribute to a translation, I have an app to help with that.  Be aware I'm currently rewriting this app so it's a lot easier to use than it currently is.  Until then, here is the older version:
https://github.com/GlowPuff/SagaTranslator/releases
