### ISSUE TITLE
UX during setup

### ISSUE THREAD

**Issue by baptistemanson** [GlowPuff/ImperialCommander2#64]
I tried to start the Hoth Campaign with Imperial Commander Windows and I couldn't scroll to view the whole map during setup, or go back to a previous instruction if I made a mistake / or Im not sure I did it correctly.

**Comment by GlowPuff** [comment]
Hello!  
- After an enemy group activates, you can always view its instructions by right clicking OR double-clicking the group's icon.
- To view the map when there are other UI elements showing, such as a text box, deployment window, or other instructions, you can click the "eye" icon in the lower left of the app.  This will hide all UI elements and allow you to freely move around the map.  Click the "eye" icon again to resume the game.

**Comment by Noldorion** [comment]
Addendum: While there is no "Undo" button to reopen closed windows, you can always open the mission log to re-read any text you might have missed.
