### ISSUE TITLE
Campaign - Dark Obsession - throws exception

### ISSUE THREAD

**Issue by Mikymart** [GlowPuff/ImperialCommander2#65]
<img width="1320" alt="Screenshot 2024-05-04 at 12 18 02" src="https://github.com/GlowPuff/ImperialCommander2/assets/145574929/c9d08d33-c5ea-40d7-b3a7-9c7e3f65808a">

Hey,
Not sure if this is problem with new update, I have not played this mission in older versions of IC2 on iOS.
Start works normally. Map is visible, basic enemy units are spawning, but problem comes when I click Continue after spawning Dark Vader. Game throws exception and there is only button to Exit app. I dont see Lukes token on the map anywhere, maybe thats the issue?

**Comment by Mikymart** [comment]
Actualy this happens on more missions where is maybe number of max rounds is not defined? Breaking point has same error.

**Comment by GlowPuff** [comment]
NICE!!! Thank you, thank you!!  All fixed, it'll go out in the next update.  The problem was caused by the countdown timer's Name property incorrectly getting set to a NULL value.  Until the fix goes out, any Mission (only a few) that uses a countdown timer will fault like this.
