### ISSUE TITLE
Text from the campaign setup help appears to be unavailable for translation.

### ISSUE THREAD

**Issue by ghost** [GlowPuff/ImperialCommander2#67]
Select a language other than English (German for example).
Create a new campaign.
In the screen where you can select heroes, click the question mark (in order to display the help)
=> Top left, it will display "Mission Type" / "Mission Name" / "Tier 1", all in English.

It looks like these texts cannot be translated to another language.
This may be text missing from the translation app ?

![image](https://github.com/GlowPuff/ImperialCommander2/assets/169312374/af52379f-5f21-4ab7-a089-0a6ea9720fa2)

**Comment by GlowPuff** [comment]
Hi ghost!  In the next update, there will be translation support for the UI items you mentioned.  It'll be up to translators to actually translate those items, which will still be in English by default.  I know French and German will be translated for sure, and maybe Spanish.
