### ISSUE TITLE
Can't open the doors for "A New Threat", no prompt

### ISSUE THREAD

**Issue by mmyang** [GlowPuff/ImperialCommander2#68]
The 3 doors in "A New Threat" cannot be clicked to open a prompt to destroy them.  I've tried clicking either side, and I've tried the mission both as part of a campaign and as stand-alone.  Both of the crates in this mission can be clicked and claimed, and the blue starting location can be clicked, it's just the doors that are not registering clicks.

Without door destruction, the mission cannot progress.  Doors work correctly for "Aftermath" and "Under Siege".

**Comment by mmyang** [comment]
Tested on Windows 10 with v.2.2.1 and v.2.2.2.

**Comment by GlowPuff** [comment]
Hello, yes, we are aware of this issue.  The file that controls the Mission is missing some data, that's why this is happening.  It'll be corrected in the next update. 👍🏻

**Comment by mmyang** [comment]
Thank you so much.  Love the app.
