### ISSUE TITLE
Modifications displayed in wrong thumbnails

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ImperialCommander2#7]
Sometimes when a group is assigned a modification (for example +10 Health), that modification is also shown in another group's thumbnail. This only happens in the thumbnail of the activation window of the group, not in the thumbnail on the enemy list on the right side of the screen.

It's tough to reproduce, but it occasionally happened in the mission "Storming the Palace" after the Rancor is deployed. (To reproduce: First defeat the Gamorrean Guards, then click the highlight and negotiate with Jabba. This deploys the Rancor with +10 Health. Now, if you go through the activations, a random group after the Rancor activated is assigned the +10 Health, too.) 

I'm still looking into how to reliably reproduce it.

**Comment by GlowPuff** [comment]
Thank you - fixed it.
