### ISSUE TITLE
Lothal4, when a hero should be set as "Wounded" "Defeat" is showing instead

### ISSUE THREAD

**Issue by MrRosendahl** [GlowPuff/ImperialCommander2#76]
Hi, 

Lothal4 mission text says "The Rebels lose when a Rebel AT-AT is defeated, _or when all heroes are wounded_". 
Expected result: "Wound" button is displayed on the first interaction on a hero.
Actual result: "Defeat" is displayed on first interaction on a hero (and on the second, but that is expected).

## Hero is wounded  
When a player is set as wounded the "Defeat" button is shown.

![Wound-20240601](https://github.com/GlowPuff/ImperialCommander2/assets/29914665/576d8348-7a08-4010-8865-9e6659b1d414)

## Hero is defeated  
When a player is defeated the button displays "Defeat" as intended.

![Defeat-20240601](https://github.com/GlowPuff/ImperialCommander2/assets/29914665/b37e46e6-838c-4044-8054-286224865a8c)

**Comment by Noldorion** [comment]
Hello!

This is correct terminology. When a figure suffers damage equivalent to its health, it is _defeated_. 

When a hero is defeated for the first time, that hero becomes _wounded_. (You flip the hero sheet.) When that hero is defeated again, the hero _withdraws_, meaning the hero is removed from play.

So "all heroes are wounded" means "all heroes have been defeated at least once".

"Defeat" and "Withdraw" are not the same 🙂

Or did I misunderstand the issue?

**Comment by MrRosendahl** [comment]
Ah, yes you're correct, I just re-read the manual on Defeated... If I recall correct the app has previously displayed Wounded and that's why we became confused when it had two buttons to select Wound or Defeat on pressing the character icon, or it might just be that we were a bit tired after a day of playing :smile: 

Anyway, I'll close this issue since its correct according to the manual.
