### ISSUE TITLE
Long mission description text is garbled

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ImperialCommander2#79]
When custom missions have a long text as a mission description, the text is not displayed correctly:

![grafik](https://github.com/GlowPuff/ImperialCommander2/assets/67169098/abd48cc4-3336-492d-80a3-6ca04c1b0db0)

**Comment by GlowPuff** [comment]
Fixed!  The text is no longer scrollable in that tiny space.  If the text is too long, it now cuts itself off with the ellipses (...) instead of overflowing.  It's also clickable, showing the full text in a popup. 👍🏻
