### ISSUE TITLE
Allies are not loaded (Exception)

### ISSUE THREAD

**Issue by Vasi1981** [GlowPuff/ImperialCommander2#84]
I tried the latest version of the app v 2.2.3 on windows. I followed the steps described in the tips and tricks to clean the previous data
(i cleaned "%localappdata%low\GlowPuff"  and the documents folder and the original data and created a new folder). When i create a new campaign before starting a mission i try to add an ally. The following error appears always:
![image](https://github.com/GlowPuff/ImperialCommander2/assets/173409360/95554d48-4f95-4c95-98ac-1cdcdeac3f65)
(simple steps)
new campaing
give name start
select hero
select > to start the first mission
Click the add ally button.

I also tried a solo mission. The error appears if i try to select an ally before i select a mission. However if i select a mission the ally list is loaded correctly.

Issue is also reproducible in android where it was a fresh install

**Comment by GlowPuff** [comment]
NICE thank you for the information!  It's fixed now.  Until I publish the next version, just make sure you have a Mission selected first, before trying to add an Ally.

As for clearing out old data:
1. press these keys: Win+R
2. This shows the "Run" dialog
3. Copy/paste "%localappdata%low\GlowPuff" without the quotes
4. Press OK
5. This will open the app's data folder, and you can delete the "Imperial Commander 2" subfolder (it'll get recreated)
6. Be aware, any old data will be gone for good, specifically any custom imported characters (ImportedCharacters subfolder), so back them up first if you have any.  They still work with the newer app.
