### ISSUE TITLE
Text overlapping/unreadable

### ISSUE THREAD

**Issue by jocelynmallon** [GlowPuff/ImperialCommander2#9]
I took the time to build ImperialCommander2 for my 12.9" iPad pro, and while most of the time it's perfect, my husband and I have noticed that when there's a lot of 'blue' unit-specific text, the text ends up overlapping/becoming unreadable.

You can see an example here:

[https://i.imgur.com/LbyA5cQ.jpg](https://i.imgur.com/LbyA5cQ.jpg)

I'm not familiar with Unity, but obviously tech-savvy enough to be able to test out any fixes/suggestions you may have, so feel free to ping me any ideas.

**Comment by GlowPuff** [comment]
Yes, great find!  Coincidentally, I recently noticed this issue myself, as well.  I fixed it just yesterday, and it's in the most recent codebase (not the one from the Release page).  On the main project page, click the green "Code" button and then "Download ZIP" to get the latest code with this fix.
